### ISSUE TITLE
Error when trying to delete account which contains more than one template

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#748] opened 2017-02-22 10:13 UTC
### Steps
- Create an account
- Create a cloudspace
- Create a VM
- Stop the VM
- Convert the VM to a template 
- Convert the VM to a template again
- Delete the account

### Actual result
The status of the account still **DESTROYING** 
and when tried to remove the account using api :  ```POST /cloudapi/accounts/delete``` 
the result was :

![aa](https://cloud.githubusercontent.com/assets/24386820/23206894/0416d5a4-f8f8-11e6-949b-c01b4c63c8a3.png)

tested on du-conv-2

### software version
JumpScale
```
Core: branch: 7.1.7 (906ce15) 2/19/2017, 9:15:27 AM
Portal: branch: 7.1.7 (21797a0) 2/21/2017, 9:41:39 AM
```
OpenvCloud
```
Core: branch: 2.1.7 (e28fb3e) 2/21/2017, 9:48:40 AM
G8VDC: branch: 2.1.7 (e9b403f) 2/20/2017, 9:05:29 PM
Selfhealing: branch: 2.1.7 (2e5b8ef) 2/19/2017, 6:22:59 PM
```
OpenvStorage:
```
openvstorage-backend-core: 1.7.9.1-1
openvstorage-health-check: 3.1.5-fargo.1-1
alba: 1.3.3
openvstorage-webapps: 2.7.9.2-1
openvstorage-backend-webapps: 1.7.9.1-1
openvstorage-core: 2.7.9.2-1
openvstorage-hc: 1.7.9.1-1
openvstorage: 2.7.9.2-1
openvstorage-backend: 1.7.9.1-1
openvstorage-sdm: 1.6.9.1-1
```

**Comment by grimpy** [comment] 2018-01-24 07:17
Duplicate of #797 closing this one as 797 contains more info

**Closed by grimpy** 2018-01-24 07:17 UTC
Labels: priority_major, type_bug
