### ISSUE TITLE
FR: Ability to create different VLANs

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1670] opened 2018-08-07 10:04 UTC
From a client request:

As previously mentioned (a few months back), we need to review the Vlan setup for our public network.

Right now all VDC have a leg in a private network and a leg in the public network ( Vlan 2300). 
(Segmentation being performed by Mikrotik)

Our limitation right now is that we cannot have a VDC sit in its own public network (for example should the customer want to have his own internet link, does not want to mix his traffic with other customer traffic or require a dedicated firewall).

That being said , we got a request from a customer having already a VDC with us ( Let's call it VDC-Internal . This VDC is using Vlan 2300 for its internet services)

Now they are planning to host public services on our cloud and the customer requested a new VDC (Let's call it VDC-Public).

VDC-Public will require access to VDC-Private ( Database access etc..)

To have the VDCs talk , we shall route the traffic via the Fortigate firewall ( VDC-Public will have its own domain)

In the past we tried to engage a conversation regarding the flexibility of the infrastructure to support more than 1 Vlan. We would like to start the discussion again and check the feasibility of same.

Can you please advise on the feasibility of the above and how this can be carried out.

**Comment by grimpy** [comment] 2018-08-14 12:15
From what is described here I see no new feature, we currently already support adding extra external networks (allowing you to pick your vlan) and assign it to a specific account.

**Comment by FastGeert** [comment] 2018-09-12 07:40
Duplicate of #1729

**Closed by FastGeert** 2018-09-12 07:40 UTC
