### ISSUE TITLE
Cannot recreate the VM with the same NAME even though deleted

### ISSUE THREAD

**Issue by abdulgig** [0-complexity/openvcloud#1494] opened 2018-04-03 10:08 UTC
#### Detailed description

Cannot recreate the VM with the same NAME even though deleted. OVC still sees the NAME and does not allow to create the VM

#### Steps to reproduce

1. Create a VM with any name , say "TESTVM"
2. Delete the VM
3. Try to create the VM again with the same name, 
4. OVC throws an error the name is already selected

#### Installation information

- environment version:
OVC 2.3.0

- Software version
JumpScale

    Core: branch: master (3f55ec4) 3/5/2018, 5:34:08 PM
    Portal: branch: master (be124d0) 3/5/2018, 2:31:52 PM

OpenvCloud

    Core: branch: master (f2c3e25) 3/6/2018, 8:12:11 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 3:56:43 PM
    Selfhealing: branch: master (4adf360) 3/4/2018, 12:58:12 PM

OpenvStorage ds1

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.8-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Comment by grimpy** [comment] 2018-04-03 10:38
Duplicate of #1346

**Closed by grimpy** 2018-04-03 10:38 UTC
