### ISSUE TITLE
Monitor and log VM status change

### ISSUE THREAD

**Issue by riaandn1** [0-complexity/openvcloud#1197] opened 2018-01-15 11:19 UTC
Whenever a VM machine is started, halted or paused, we shoud log who has done this and how. If this is done via OVC then  this should be logged as such. If this is done via a command other than via OVC then this shoudl be logged.

**Comment by FastGeert** [comment] 2018-01-19 15:10
Duplicate of #1160 & #1159

**Closed by FastGeert** 2018-01-19 15:10 UTC
Labels: priority_minor, type_feature
