### ISSUE TITLE
OVC 2.3.0 cannot delete cloud space even when it doesn't contain any VMs 

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1472] opened 2018-03-27 11:02 UTC
As per attached images cloudspace cannot be deleted even though there is no vm on it.

<img width="1427" alt="screen shot 2018-03-27 at 13 59 56" src="https://user-images.githubusercontent.com/3851678/37963599-70b3e8ba-31c7-11e8-8560-c28c4355fcad.png">
<img width="1440" alt="screen shot 2018-03-27 at 13 59 39" src="https://user-images.githubusercontent.com/3851678/37963604-759a0dbe-31c7-11e8-9058-010e1a183edf.png">

**Comment by alichaddad** [comment] 2018-04-01 08:51
Duplicate of https://github.com/0-complexity/openvcloud/issues/1389

**Closed by alichaddad** 2018-04-01 08:51 UTC
