### ISSUE TITLE
Schedule self healing script from portal

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1043] opened 2017-12-04 16:22 UTC
We need to prevent ssh access to nodes as much as possible. 
In order to achieve that it must be possible to add jumpscripts through the portal, and test drive them via the portal, examining the result via the portal.

**Comment by grimpy** [comment] 2018-01-31 08:39
Duplicate of #976

**Comment by ahmedelsayed-93** [comment] 2018-02-27 12:42
found this issues :

### Issue #1

#### Steps:
- open jumpscript page
- choose any jumpscript for example ```memory_physical_stats```
- from action menu click on execute jumpscript.
- put negative value on nodeid field & click confirm.

#### Expected result
invalid node id error

#### Actual result
it took long time loading, then returned this error
![image](https://user-images.githubusercontent.com/24386820/36729165-ef5a7b5a-1bcb-11e8-9728-0bc6144de1ec.png)
 
### Issue #2
#### Steps:
- same steps of issue one except the last one.
- add valid node id and click confirm
- then open the provided  job link

#### result

![image](https://user-images.githubusercontent.com/24386820/36729279-577d7d5e-1bcc-11e8-8d5b-004cc75797fe.png)

**Comment by islamTaha12** [comment] 2018-03-01 13:35
steps: 
as here https://github.com/0-complexity/openvcloud/issues/1043#issuecomment-368861065

**Actual result:**
It returns invalid job id link, however, If you go to the jobs page, u will find the job in the table but with different url.
![image](https://user-images.githubusercontent.com/17981089/36846958-58b89010-1d65-11e8-98a5-039c1c2f5f33.png)
![image](https://user-images.githubusercontent.com/17981089/36846965-61529568-1d65-11e8-8e2d-5e9eceb880c8.png)

Related issue:
The execution script doesn't execute the command as I send `pwd` as a cmd but here is the actual result
![image](https://user-images.githubusercontent.com/17981089/36847170-152df1d6-1d66-11e8-94f1-ce1dfbf353a3.png)

**Comment by ahmedelsayed-93** [comment] 2018-03-04 09:12
Issue #1 in this comment https://github.com/0-complexity/openvcloud/issues/1043#issuecomment-368861065 stil exists

**Comment by abdulrahmantkhalifa** [comment] 2018-03-04 10:24
your env out of date

**Comment by ahmedelsayed-93** [comment] 2018-03-04 13:07
JumpScale

    Core: branch: master (0fdeaf3) 3/2/2018, 8:41:51 PM
    Portal: branch: master (3df0a29) 3/1/2018, 8:00:47 PM

OpenvCloud

    Core: branch: master (11f0302) 3/4/2018, 9:20:46 AM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (8f2a952) 3/1/2018, 5:40:22 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Closed by ahmedelsayed-93** 2018-03-04 13:07 UTC
Labels: state_verification, type_feature
