### ISSUE TITLE
Freely choose memory and #cpu

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1329] opened 2018-02-09 08:11 UTC
Besides predefined sizes we need to be able to create a vm with x amount of memory (MiB) and a number of vcpu's (n+1)

**Comment by grimpy** [comment] 2018-04-13 13:03
Duplicate of https://github.com/0-complexity/openvcloud/issues/1424

**Closed by grimpy** 2018-04-13 13:03 UTC
Labels: type_feature
