### ISSUE TITLE
Make sure that redis ins't exposed in production mode

### ISSUE THREAD

**Issue by islamTaha12** [0-complexity/openvcloud#1326] opened 2018-02-05 09:55 UTC
We need to make sure that redis port isn't public exposed in the production mode. As I found that underdevelopment mode redis is still exposed over 9999 port

**Comment by FastGeert** [comment] 2018-02-09 08:13
Is this on kubernetes deployed controller?

**Comment by islamTaha12** [comment] 2018-03-16 15:35
@FastGeert it was in 2.3.0 so I think yes But Jo told me that it's only exposed in development mode

**Comment by dinosn** [comment] 2018-06-12 06:04
Apparently it's not the case, https://github.com/0-complexity/openvcloud/issues/1565 it's still open in production

**Comment by grimpy** [comment] 2018-07-08 07:07
This is by design all redises on the nodes are open listening on 0.0.0.0
This is because on the  controller we collect all the statistics of all the nodes.
However we should always make sure the firewall on the controllers does not allow incoming traffic to the redis ports via the public IP

**Comment by FastGeert** [comment] 2018-07-09 09:52
@dinosn & @grimpy lets talk.

**Comment by FastGeert** [comment] 2018-07-09 12:39
Actual problem will be resolved in #1602

**Comment by dinosn** [comment] 2018-08-09 08:55
This issue compromised 4 environments. Please take actions faster on such cases. We have 4 environments added to a kryptomining grid not of our own.

**Comment by grimpy** [comment] 2018-08-09 10:00
https://github.com/0-complexity/911builder/commit/c4c4c94109562bd739464b8017858dad1a99649c

was fixed here (and some extra commits in the same release)

**Closed by grimpy** 2018-08-09 10:00 UTC
Labels: priority_major, type_feature
