### ISSUE TITLE
Provide the ability from the panel to pause all vm in the whole environment

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1067] opened 2017-12-07 10:15 UTC
This is a feature request. 

   Under some cases like a network change for upgrades, an update that requires downtime, a hardware issue and so on we problem with the running VMs as they are losing their filesystem. 

This might be for some minutes, or some seconds depending on the outage window. 

I would like to request the option to pause all VMs from the panel so the systems won't lose their filesystems and corrupt files during the operation.

In the same option the way to start all previously paused VMs should exist.

**Comment by FastGeert** [comment] 2017-12-08 07:30
Should not be implemented as a builtin feature.

Can be made through the scheduling of JumpScripts as described in #1043

**Comment by grimpy** [comment] 2018-02-18 12:08
Duplicate of #1043

**Closed by grimpy** 2018-02-18 12:08 UTC
Labels: type_feature
