### ISSUE TITLE
VM > Convert to Template fails

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/openvcloud#850] opened 2017-05-10 08:53 UTC
Tested on https://ma-g8-1.demo.greenitglobe.com

When trying the **Convert To Template** action on VM [myowncloud1](https://ma-g8-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=2192):

![screen shot 2017-05-10 at 10 41 48](https://cloud.githubusercontent.com/assets/13795109/25890689/c231c898-356e-11e7-984d-66fe4f391629.png)

![screen shot 2017-05-10 at 10 42 52](https://cloud.githubusercontent.com/assets/13795109/25890546/2769f204-356e-11e7-82b8-576bc0814170.png)

Audit:
https://ma-g8-1.demo.greenitglobe.com/grid/audit?id=be11c900-712d-4d9b-9b18-2060beca9114
![screen shot 2017-05-10 at 10 47 12](https://cloud.githubusercontent.com/assets/13795109/25890527/1c038038-356e-11e7-829c-d6935ea7b13b.png)

Error Condition:

![screen shot 2017-05-10 at 10 49 17](https://cloud.githubusercontent.com/assets/13795109/25890610/6c187d12-356e-11e7-8cd2-ee58e16e0ec0.png)

![screen shot 2017-05-10 at 10 50 24](https://cloud.githubusercontent.com/assets/13795109/25890630/834012de-356e-11e7-815e-d579a26a2615.png)

As result under Images:

![screen shot 2017-05-10 at 11 01 46](https://cloud.githubusercontent.com/assets/13795109/25891109/1fb8c5d8-3570-11e7-895c-847fed2151db.png)

And on the Image Details page:

![screen shot 2017-05-10 at 11 02 29](https://cloud.githubusercontent.com/assets/13795109/25891139/38d75e44-3570-11e7-8ad2-13a2d54be427.png)

**Comment by FastGeert** [comment] 2018-01-05 14:46
Duplicate of #930. Will be solved in 2.3.1

**Closed by FastGeert** 2018-01-05 14:46 UTC
Labels: type_bug
